sudo: false
language: node_js
node_js:
    - "4"

branches:
    only:
        - master
        - dev

install:
    - npm install

cache:
    directories:
        - node_modules

script:
    npm test

deploy:
  - provider: s3
    access_key_id: $S3_ACCESS_KEY_ID
    secret_access_key: $S3_SECRET_ACCESS_KEY
    bucket: "pixi-gl-core-branch"
    skip_cleanup: true
    acl: public_read
    local_dir: bin
    upload-dir: "$TRAVIS_BRANCH"
    region: eu-west-1
    on:
        all_branches: true
  - provider: s3
    access_key_id: $S3_ACCESS_KEY_ID
    secret_access_key: $S3_SECRET_ACCESS_KEY
    bucket: "pixi-gl-core"
    skip_cleanup: true
    acl: public_read
    local_dir: bin
    upload-dir: "$TRAVIS_TAG"
    region: eu-west-1
    on: 
        tags: true